### ISSUE TITLE
Wrong URL in README.md / Elaborate deep sleep documentation

### ISSUE THREAD

**Issue by rradar** [boneskull/shtshow#1]
Hi there,

the link under

**Installation**
- 6 . Follow Homie's setup instructions (https://homie-esp8266.readme.io/docs/getting-started)

is throwing a **404**. It says documentation moved here: http://marvinroger.github.io/homie-esp8266/

**Other question I have if it's possible to elaborate deep sleep documentation a little.**

Special these to points - how can I achieve this, what need's to be done?:

- For the D1 Mini, I had best results with WAKE_RF_DEFAULT when entering deep sleep.
- Likewise, I'm not sure clock stretching works very well on an ESP8266, so we're using the SHT30's "periodic" mode.

**Comment by rradar** [comment]
Actually the right link would be this one for the stable version:

http://marvinroger.github.io/homie-esp8266/docs/stable/2.-Getting-started/

**Comment by boneskull** [comment]
Thanks; I fixed the URL.

This firmware leverages deep sleep out-of-the-box, so you don't have to change anything.

> For the D1 Mini, I had best results with WAKE_RF_DEFAULT when entering deep sleep.

There are various other constants available when calling `ESP.deepSleep()`; `WAKE_RF_DEFAULT` is the one that worked for me.

> Likewise, I'm not sure clock stretching works very well on an ESP8266, so we're using the SHT30's "periodic" mode.

Clock-stretching is another method to get data out of the SHT30, but the ESP8266 has limited (no?) support for this.  Therefore, we use the "periodic" method.  See the SHT30's datasheet for more info.
