### ISSUE TITLE
Provide a ready-to-flash-bin in the release section

### ISSUE THREAD

**Issue by pidiet** [boneskull/shtshow#2]
Hello @boneskull ,

is it possible that you publish a binary ready to flash with esptool.py directly to the wemos?

Would be really glad for this!

Thank's!

**Comment by boneskull** [comment]
Why is this needed?

**Comment by rradar** [comment]
I like the idea too.

It's just a little easier and you don't have the hassle using atom/platformio etc. This tools have quite a lot dependencies (I think over 100MB in total) and if you don't have them already and you are living on the countryside it can take a couple of hours or even days (there is still a lot's of people with 56kbit/s or an unreliable downlink!) to get this up and running.

If there would be a tiny (500kb) binary file it's even possible for far remote areas to get this in a reasonable time and be able to use this nice piece of software.

And as there is no hard coded credentials in the code it should be no problem to provide a binary.

Just my two cents.

**Comment by pidiet** [comment]
@boneskull just because it's less work =)

But the small or limited bandwidth is also a valid point @rradar

**Comment by boneskull** [comment]
This is done.  See [release v0.2.0](https://github.com/boneskull/shtshow/releases/tag/v0.2.0)

**Comment by pidiet** [comment]
Great! Thank's a lot!

**Comment by rradar** [comment]
Yea, very nice!
