### ISSUE TITLE
Which mqtt topics are used to publish data?

### ISSUE THREAD

**Issue by rradar** [boneskull/shtshow#5]
After I got it finally running and the sensor running (can see in serial console) I wonder which topics are used to publish the temperature and humidity? I searched the source code but couldn't figure out what's used

I tried many of them...

> homie/temp
> homie/temperature
> homie/humidity
> homie/sensor/temp
> homie/sensor/temperature
> homie/sensor/humidity
> homie/enviroment/temp
> homie/enviroment/temperature
> homie/enviroment/humanity
> homie/sensor/enviroment/temp
> homie/sensor/enviroment/temperature
> homie/sensor/enviroment/humidity

...and more

I don't find the right topic :(

**Comment by rradar** [comment]
to many...

**Comment by boneskull** [comment]
See [the Homie convention](https://github.com/homieiot/convention) for more explanation.

There are two "nodes", which are `temperature` and `humidity`.  Both publish the unit used and the value under two different properties:

```
<root>/<device-id>/temperature/unit
<root>/<device-id>/temperature/value
<root>/<device-id>/humidity/unit
<root>/<device-id>/humidity/value
```

By default, the unit of temperature is "F" (I'm in the US) and the unit of humidity is "RH" (relative humidity, which is a percentage).
